package vn.softech.hibernate;
// Generated Feb 27, 2012 10:59:38 AM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblCongDan generated by hbm2java
 */
public class TblCongDan  implements java.io.Serializable {


     private Long congDanId;
     private String ten;
     private String chucDanh;
     private boolean gioiTinh;
     private String soCmnd;
     private String noiCapCmnd;
     private Date ngayCapCmnd;
     private String diaChi;
     private String email;
     private String soDienThoai;
     private Date created;
     private Date modified;
     private byte status;
     private List<TblTtpdgmsts> tblTtpdgmstses = new ArrayList<TblTtpdgmsts>();
     private List<TblTtpapbdtns> tblTtpapbdtnses = new ArrayList<TblTtpapbdtns>();
     private List<TblTtcgcndkmsxdcb> tblTtcgcndkmsxdcbs = new ArrayList<TblTtcgcndkmsxdcb>();
     private List<TblTtcmsdvsdns>  tblTtcmsdvsdnses = new ArrayList<TblTtcmsdvsdns>();
    public TblCongDan() {
    }

	
    public TblCongDan(String ten, boolean gioiTinh, String soCmnd, String noiCapCmnd, Date ngayCapCmnd, String diaChi, Date created, Date modified, byte status) {
        this.ten = ten;
        this.gioiTinh = gioiTinh;
        this.soCmnd = soCmnd;
        this.noiCapCmnd = noiCapCmnd;
        this.ngayCapCmnd = ngayCapCmnd;
        this.diaChi = diaChi;
        this.created = created;
        this.modified = modified;
        this.status = status;
    }
    public TblCongDan(String ten, String chucDanh, boolean gioiTinh, String soCmnd, String noiCapCmnd, Date ngayCapCmnd, String diaChi, String email, String soDienThoai, Date created, Date modified, byte status, List<TblTtpdgmsts> tblTtpdgmstses, List<TblTtpapbdtns> tblTtpapbdtnses, List<TblTtcgcndkmsxdcb> tblTtcgcndkmsxdcbs, List<TblTtcmsdvsdns> tblTtcmsdvsdnses) {
       this.ten = ten;
       this.chucDanh = chucDanh;
       this.gioiTinh = gioiTinh;
       this.soCmnd = soCmnd;
       this.noiCapCmnd = noiCapCmnd;
       this.ngayCapCmnd = ngayCapCmnd;
       this.diaChi = diaChi;
       this.email = email;
       this.soDienThoai = soDienThoai;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.tblTtpdgmstses = tblTtpdgmstses;
       this.tblTtpapbdtnses = tblTtpapbdtnses;
       this.tblTtcgcndkmsxdcbs = tblTtcgcndkmsxdcbs;
       this.setTblTtcmsdvsdnses(tblTtcmsdvsdnses);
    }
   
    public Long getCongDanId() {
        return this.congDanId;
    }
    
    public void setCongDanId(Long congDanId) {
        this.congDanId = congDanId;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getChucDanh() {
        return this.chucDanh;
    }
    
    public void setChucDanh(String chucDanh) {
        this.chucDanh = chucDanh;
    }
    public boolean isGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getSoCmnd() {
        return this.soCmnd;
    }
    
    public void setSoCmnd(String soCmnd) {
        this.soCmnd = soCmnd;
    }
    public String getNoiCapCmnd() {
        return this.noiCapCmnd;
    }
    
    public void setNoiCapCmnd(String noiCapCmnd) {
        this.noiCapCmnd = noiCapCmnd;
    }
    public Date getNgayCapCmnd() {
        return this.ngayCapCmnd;
    }
    
    public void setNgayCapCmnd(Date ngayCapCmnd) {
        this.ngayCapCmnd = ngayCapCmnd;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public List<TblTtpdgmsts> getTblTtpdgmstses() {
        return this.tblTtpdgmstses;
    }
    
    public void setTblTtpdgmstses(List<TblTtpdgmsts> tblTtpdgmstses) {
        this.tblTtpdgmstses = tblTtpdgmstses;
    }
    public List<TblTtpapbdtns> getTblTtpapbdtnses() {
        return this.tblTtpapbdtnses;
    }
    
    public void setTblTtpapbdtnses(List<TblTtpapbdtns> tblTtpapbdtnses) {
        this.tblTtpapbdtnses = tblTtpapbdtnses;
    }
    public List<TblTtcgcndkmsxdcb> getTblTtcgcndkmsxdcbs() {
        return this.tblTtcgcndkmsxdcbs;
    }
    
    public void setTblTtcgcndkmsxdcbs(List<TblTtcgcndkmsxdcb> tblTtcgcndkmsxdcbs) {
        this.tblTtcgcndkmsxdcbs = tblTtcgcndkmsxdcbs;
    }


	public List<TblTtcmsdvsdns> getTblTtcmsdvsdnses() {
		return tblTtcmsdvsdnses;
	}


	public void setTblTtcmsdvsdnses(List<TblTtcmsdvsdns> tblTtcmsdvsdnses) {
		this.tblTtcmsdvsdnses = tblTtcmsdvsdnses;
	}




}


