package vn.softech.hibernate;

// Generated Apr 23, 2012 5:48:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblCktcCm generated by hbm2java
 */
public class TblCktcCm implements java.io.Serializable {

	private Long cktcCmId;
	private String name;
	private Boolean hienThi;
	private Byte priority;
	private Date created;
	private Date modified;
	private Byte status;
	private List<TblCktc> tblCktcs = new ArrayList<TblCktc>();

	public TblCktcCm() {
	}

	public TblCktcCm(String name) {
		this.name = name;
	}

	public TblCktcCm(String name, Boolean hienThi, Byte priority, Date created,
			Date modified, Byte status, Set tblCktcs) {
		this.name = name;
		this.hienThi = hienThi;
		this.priority = priority;
		this.created = created;
		this.modified = modified;
		this.status = status;
		this.tblCktcs =  new ArrayList<TblCktc>();
	}

	public Long getCktcCmId() {
		return this.cktcCmId;
	}

	public void setCktcCmId(Long cktcCmId) {
		this.cktcCmId = cktcCmId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getHienThi() {
		return this.hienThi;
	}

	public void setHienThi(Boolean hienThi) {
		this.hienThi = hienThi;
	}

	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public List<TblCktc> getTblCktcs() {
		return this.tblCktcs;
	}

	public void setTblCktcs(List<TblCktc> tblCktcs) {
		this.tblCktcs = tblCktcs;
	}

}
