package vn.softech.hibernate;
// Generated Feb 2, 2012 11:29:37 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblDocument generated by hbm2java
 */
public class TblDocument  implements java.io.Serializable {


     private Long documentId;
     private String name;
     private byte[] data;
     private Date created;
     private byte status;

    public TblDocument() {
    }

    public TblDocument(String name, byte[] data, Date created, byte status) {
       this.name = name;
       this.data = data;
       this.created = created;
       this.status = status;
    }
   
    public Long getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(Long documentId) {
        this.documentId = documentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


