package vn.softech.hibernate;
// Generated Mar 14, 2012 10:23:18 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblGiaDat generated by hbm2java
 */
public class TblGiaDat  implements java.io.Serializable {


     private Long giaDatId;
     private TblUsers tblUsers;
     private TblXaPhuong tblXaPhuong;
     private TblGiaDat tblGiaDat;
     private TblQuanHuyen tblQuanHuyen;
     private Boolean parent;
     private Long nam;
     private String tenDuongPho;
     private String ghiChu;
     private Byte loaiDuong;
     private String khuVuc;
     private BigDecimal heSo;
     private Long donGia;
     private Date created;
     private Date modified;
     private Byte status;
     private List<TblGiaDat> tblGiaDats = new ArrayList<TblGiaDat>();

    public TblGiaDat() {
    }

	
    public TblGiaDat(TblUsers tblUsers, String tenDuongPho, Date created, Date modified) {
        this.tblUsers = tblUsers;
        this.tenDuongPho = tenDuongPho;
        this.created = created;
        this.modified = modified;
    }
    public TblGiaDat(TblUsers tblUsers, TblXaPhuong tblXaPhuong, TblGiaDat tblGiaDat, TblQuanHuyen tblQuanHuyen, Boolean parent, Long nam, String tenDuongPho, String ghiChu, Byte loaiDuong, String khuVuc, BigDecimal heSo, Long donGia, Date created, Date modified, Byte status, List<TblGiaDat> tblGiaDats) {
       this.tblUsers = tblUsers;
       this.tblXaPhuong = tblXaPhuong;
       this.tblGiaDat = tblGiaDat;
       this.tblQuanHuyen = tblQuanHuyen;
       this.parent = parent;
       this.nam = nam;
       this.tenDuongPho = tenDuongPho;
       this.ghiChu = ghiChu;
       this.loaiDuong = loaiDuong;
       this.khuVuc = khuVuc;
       this.heSo = heSo;
       this.donGia = donGia;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.tblGiaDats = tblGiaDats;
    }
   
    public Long getGiaDatId() {
        return this.giaDatId;
    }
    
    public void setGiaDatId(Long giaDatId) {
        this.giaDatId = giaDatId;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public TblXaPhuong getTblXaPhuong() {
        return this.tblXaPhuong;
    }
    
    public void setTblXaPhuong(TblXaPhuong tblXaPhuong) {
        this.tblXaPhuong = tblXaPhuong;
    }
    public TblGiaDat getTblGiaDat() {
        return this.tblGiaDat;
    }
    
    public void setTblGiaDat(TblGiaDat tblGiaDat) {
        this.tblGiaDat = tblGiaDat;
    }
    public TblQuanHuyen getTblQuanHuyen() {
        return this.tblQuanHuyen;
    }
    
    public void setTblQuanHuyen(TblQuanHuyen tblQuanHuyen) {
        this.tblQuanHuyen = tblQuanHuyen;
    }
    public Boolean getParent() {
        return this.parent;
    }
    
    public void setParent(Boolean parent) {
        this.parent = parent;
    }
    public Long getNam() {
        return this.nam;
    }
    
    public void setNam(Long nam) {
        this.nam = nam;
    }
    public String getTenDuongPho() {
        return this.tenDuongPho;
    }
    
    public void setTenDuongPho(String tenDuongPho) {
        this.tenDuongPho = tenDuongPho;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Byte getLoaiDuong() {
        return this.loaiDuong;
    }
    
    public void setLoaiDuong(Byte loaiDuong) {
        this.loaiDuong = loaiDuong;
    }
    public String getKhuVuc() {
        return this.khuVuc;
    }
    
    public void setKhuVuc(String khuVuc) {
        this.khuVuc = khuVuc;
    }
    public BigDecimal getHeSo() {
        return this.heSo;
    }
    
    public void setHeSo(BigDecimal heSo) {
        this.heSo = heSo;
    }
    public Long getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(Long donGia) {
        this.donGia = donGia;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public List<TblGiaDat> getTblGiaDats() {
        return this.tblGiaDats;
    }
    
    public void setTblGiaDats(List<TblGiaDat> tblGiaDats) {
        this.tblGiaDats = tblGiaDats;
    }




}


