package vn.softech.hibernate;
// Generated Jan 18, 2012 9:33:11 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblGioiThieu generated by hbm2java
 */
public class TblGioiThieu  implements java.io.Serializable {


     private Long gioiThieuId;
     private String titleMenu;
     private String title;
     private String content;
     private Date created;
     private Date modified;
     private byte status;
     private boolean active;
     private byte usersId;
     private Long parentId;
     private Byte priority;
     
    public TblGioiThieu() {
    }

	
    public TblGioiThieu(String titleMenu, String title, String content, Date created, Date modified, byte status, boolean active, byte usersId) {
        this.titleMenu = titleMenu;
        this.title = title;
        this.content = content;
        this.created = created;
        this.modified = modified;
        this.status = status;
        this.active = active;
        this.usersId = usersId;
    }
    public TblGioiThieu(String titleMenu, String title, String content, Date created, Date modified, byte status, boolean active, byte usersId, Long parentId) {
       this.titleMenu = titleMenu;
       this.title = title;
       this.content = content;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.active = active;
       this.usersId = usersId;
       this.parentId = parentId;
    }
   
    public Long getGioiThieuId() {
        return this.gioiThieuId;
    }
    
    public void setGioiThieuId(Long gioiThieuId) {
        this.gioiThieuId = gioiThieuId;
    }
    public String getTitleMenu() {
        return this.titleMenu;
    }
    
    public void setTitleMenu(String titleMenu) {
        this.titleMenu = titleMenu;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public byte getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(byte usersId) {
        this.usersId = usersId;
    }
    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }


	public Byte getPriority() {
		return priority;
	}


	public void setPriority(Byte priority) {
		this.priority = priority;
	}




}


