package vn.softech.hibernate;

// Generated Jul 10, 2012 8:21:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblGiaThiTruong generated by hbm2java
 */
public class TblGiaThiTruong implements java.io.Serializable {

	private Long giaThiTruongId;
	private Long giattCatalogId;
	private Byte type;
	private String title;
	private String content;
	private Date created;
	private Date modified;
	private byte status;
	private boolean active;
	private Byte usersId;

	public TblGiaThiTruong() {
	}

	public TblGiaThiTruong(String title, String content, Date created,
			Date modified, byte status, boolean active) {
		this.title = title;
		this.content = content;
		this.created = created;
		this.modified = modified;
		this.status = status;
		this.active = active;
	}

	public TblGiaThiTruong(Long giattCatalogId, Byte type, String title,
			String content, Date created, Date modified, byte status,
			boolean active, Byte usersId) {
		this.giattCatalogId = giattCatalogId;
		this.type = type;
		this.title = title;
		this.content = content;
		this.created = created;
		this.modified = modified;
		this.status = status;
		this.active = active;
		this.usersId = usersId;
	}

	public Long getGiaThiTruongId() {
		return this.giaThiTruongId;
	}

	public void setGiaThiTruongId(Long giaThiTruongId) {
		this.giaThiTruongId = giaThiTruongId;
	}

	public Long getGiattCatalogId() {
		return this.giattCatalogId;
	}

	public void setGiattCatalogId(Long giattCatalogId) {
		this.giattCatalogId = giattCatalogId;
	}

	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Byte getUsersId() {
		return this.usersId;
	}

	public void setUsersId(Byte usersId) {
		this.usersId = usersId;
	}

}
