package vn.softech.hibernate;
// Generated Feb 3, 2012 4:17:59 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblGroups generated by hbm2java
 */
public class TblGroups  implements java.io.Serializable {

     private Long groupsId;
     private String name;
     private Date created;
     private Date modified;
     private Byte priority;
     private Byte status;
     private List<TblUsersGroups> tblUsersGroupses = new ArrayList<TblUsersGroups>();
     private List<TblUrlsGroups> tblUrlsGroupses = new ArrayList<TblUrlsGroups>();

    public TblGroups() {
    }

	
    public TblGroups(String name, Date created, Date modified) {
        this.name = name;
        this.created = created;
        this.modified = modified;
    }
    public TblGroups(String name, Date created, Date modified, Byte priority, Byte status, List<TblUsersGroups> tblUsersGroupses, List<TblUrlsGroups> tblUrlsGroupses) {
       this.name = name;
       this.created = created;
       this.modified = modified;
       this.priority = priority;
       this.status = status;
       this.tblUsersGroupses = tblUsersGroupses;
       this.tblUrlsGroupses = tblUrlsGroupses;
    }
   
    public Long getGroupsId() {
        return this.groupsId;
    }
    
    public void setGroupsId(Long groupsId) {
        this.groupsId = groupsId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Byte getPriority() {
        return this.priority;
    }
    
    public void setPriority(Byte priority) {
        this.priority = priority;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public List<TblUsersGroups> getTblUsersGroupses() {
        return this.tblUsersGroupses;
    }
    
    public void setTblUsersGroupses(List<TblUsersGroups> tblUsersGroupses) {
        this.tblUsersGroupses = tblUsersGroupses;
    }
    public List<TblUrlsGroups> getTblUrlsGroupses() {
        return this.tblUrlsGroupses;
    }
    
    public void setTblUrlsGroupses(List<TblUrlsGroups> tblUrlsGroupses) {
        this.tblUrlsGroupses = tblUrlsGroupses;
    }




}


