package vn.softech.hibernate;
// Generated Jan 18, 2012 3:03:09 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblHinhAnh generated by hbm2java
 */
public class TblHinhAnh  implements java.io.Serializable {


     private Integer hinhAnhId;
     private String title;
     private String path;
     private Date created;
     private Date modified;
     private byte status;
     private Integer usersId;

    public TblHinhAnh() {
    }

	
    public TblHinhAnh(String title, String path, Date created, Date modified, byte status) {
        this.title = title;
        this.path = path;
        this.created = created;
        this.modified = modified;
        this.status = status;
    }
    public TblHinhAnh(String title, String path, Date created, Date modified, byte status, Integer usersId) {
       this.title = title;
       this.path = path;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.usersId = usersId;
    }
   
    public Integer getHinhAnhId() {
        return this.hinhAnhId;
    }
    
    public void setHinhAnhId(Integer hinhAnhId) {
        this.hinhAnhId = hinhAnhId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Integer getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }




}


