package vn.softech.hibernate;
// Generated Feb 7, 2012 11:41:35 AM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblLdLoaiVb generated by hbm2java
 */
public class TblLdLoaiVb  implements java.io.Serializable {
	
     private Short ldLoaiVbId;
     private String name;
     private Byte type;
     private Date created;
     private Date modified;
     private byte status;
     private Byte macDinh;
     private Integer usersId;
     private List<TblLegalDocuments> tblLegalDocumentses = new ArrayList<TblLegalDocuments>();

    public TblLdLoaiVb() {
    }

	
    public TblLdLoaiVb(String name, Date created, Date modified, byte status) {
        this.name = name;
        this.created = created;
        this.modified = modified;
        this.status = status;
    }
    public TblLdLoaiVb(String name, Date created, Date modified, byte status, Byte macDinh, Integer usersId, List<TblLegalDocuments> tblLegalDocumentses) {
       this.name = name;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.macDinh = macDinh;
       this.usersId = usersId;
       this.tblLegalDocumentses = tblLegalDocumentses;
    }
   
    public Short getLdLoaiVbId() {
        return this.ldLoaiVbId;
    }
    
    public void setLdLoaiVbId(Short ldLoaiVbId) {
        this.ldLoaiVbId = ldLoaiVbId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Byte getMacDinh() {
        return this.macDinh;
    }
    
    public void setMacDinh(Byte macDinh) {
        this.macDinh = macDinh;
    }
    public Integer getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }
    public List<TblLegalDocuments> getTblLegalDocumentses() {
        return this.tblLegalDocumentses;
    }
    
    public void setTblLegalDocumentses(List<TblLegalDocuments> tblLegalDocumentses) {
        this.tblLegalDocumentses = tblLegalDocumentses;
    }


	public Byte getType() {
		return type;
	}


	public void setType(Byte type) {
		this.type = type;
	}




}


