package vn.softech.hibernate;
// Generated Feb 3, 2012 9:35:09 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblLdLinhVuc generated by hbm2java
 */
public class TblLdLinhVuc  implements java.io.Serializable {


     private Short ldLinhVucId;
     private Byte type;
     private String name;
     private Date created;
     private Date modified;
     private byte status;
     private boolean macDinh;
     private Integer usersId;

    public TblLdLinhVuc() {
    }

	
    public TblLdLinhVuc(String name, Date created, Date modified, byte status, boolean macDinh) {
        this.name = name;
        this.created = created;
        this.modified = modified;
        this.status = status;
        this.macDinh = macDinh;
    }
    public TblLdLinhVuc(String name, Date created, Date modified, byte status, boolean macDinh, Integer usersId) {
       this.name = name;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.macDinh = macDinh;
       this.usersId = usersId;
    }
   
    public Short getLdLinhVucId() {
        return this.ldLinhVucId;
    }
    
    public void setLdLinhVucId(Short ldLinhVucId) {
        this.ldLinhVucId = ldLinhVucId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public boolean isMacDinh() {
        return this.macDinh;
    }
    
    public void setMacDinh(boolean macDinh) {
        this.macDinh = macDinh;
    }
    public Integer getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }


	public Byte getType() {
		return type;
	}


	public void setType(Byte type) {
		this.type = type;
	}




}


