package vn.softech.hibernate;
// Generated Feb 7, 2012 11:41:35 AM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblLdCoQuan generated by hbm2java
 */
public class TblLdCoQuan  implements java.io.Serializable {


     private Short ldCoQuanId;
     private TblLdCap tblLdCap;
     private Byte type;
     private String name;
     private byte status;
     private Date created;
     private Date modified;
     private Integer usersId;
     private boolean macDinh;
     private List<TblLegalDocuments> tblLegalDocumentses = new ArrayList<TblLegalDocuments>();

    public TblLdCoQuan() {
    }

	
    public TblLdCoQuan(TblLdCap tblLdCap, String name, byte status, Date created, Date modified, boolean macDinh) {
        this.tblLdCap = tblLdCap;
        this.name = name;
        this.status = status;
        this.created = created;
        this.modified = modified;
        this.macDinh = macDinh;
    }
    public TblLdCoQuan(TblLdCap tblLdCap, String name, byte status, Date created, Date modified, Integer usersId, boolean macDinh, List<TblLegalDocuments> tblLegalDocumentses) {
       this.tblLdCap = tblLdCap;
       this.name = name;
       this.status = status;
       this.created = created;
       this.modified = modified;
       this.usersId = usersId;
       this.macDinh = macDinh;
       this.tblLegalDocumentses = tblLegalDocumentses;
    }
   
    public Short getLdCoQuanId() {
        return this.ldCoQuanId;
    }
    
    public void setLdCoQuanId(Short ldCoQuanId) {
        this.ldCoQuanId = ldCoQuanId;
    }
    public TblLdCap getTblLdCap() {
        return this.tblLdCap;
    }
    
    public void setTblLdCap(TblLdCap tblLdCap) {
        this.tblLdCap = tblLdCap;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Integer getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }
    public boolean isMacDinh() {
        return this.macDinh;
    }
    
    public void setMacDinh(boolean macDinh) {
        this.macDinh = macDinh;
    }
    public List<TblLegalDocuments> getTblLegalDocumentses() {
        return this.tblLegalDocumentses;
    }
    
    public void setTblLegalDocumentses(List<TblLegalDocuments> tblLegalDocumentses) {
        this.tblLegalDocumentses = tblLegalDocumentses;
    }


	public Byte getType() {
		return type;
	}


	public void setType(Byte type) {
		this.type = type;
	}




}


