package vn.softech.hibernate;
// Generated Mar 24, 2012 9:50:03 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtcmsdvsdnsChuyenhs generated by hbm2java
 */
public class TblTtcmsdvsdnsChuyenhs  implements java.io.Serializable {


     private Long ttcmsdvsdnsChuyenhsId;
     private TblUsers tblUsersByUsersChuyenId;
     private TblUsers tblUsersByUsersNhanId;
     private TblTtcmsdvsdns tblTtcmsdvsdns;
     private Date ngayChuyen;
     private String ghiChu;
     private Byte status;

    public TblTtcmsdvsdnsChuyenhs() {
    }

	
    public TblTtcmsdvsdnsChuyenhs(TblUsers tblUsersByUsersChuyenId, TblUsers tblUsersByUsersNhanId, TblTtcmsdvsdns tblTtcmsdvsdns, Date ngayChuyen) {
        this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
        this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
        this.tblTtcmsdvsdns = tblTtcmsdvsdns;
        this.ngayChuyen = ngayChuyen;
    }
    public TblTtcmsdvsdnsChuyenhs(TblUsers tblUsersByUsersChuyenId, TblUsers tblUsersByUsersNhanId, TblTtcmsdvsdns tblTtcmsdvsdns, Date ngayChuyen, String ghiChu, Byte status) {
       this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
       this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
       this.tblTtcmsdvsdns = tblTtcmsdvsdns;
       this.ngayChuyen = ngayChuyen;
       this.ghiChu = ghiChu;
       this.status = status;
    }
   
    public Long getTtcmsdvsdnsChuyenhsId() {
        return this.ttcmsdvsdnsChuyenhsId;
    }
    
    public void setTtcmsdvsdnsChuyenhsId(Long ttcmsdvsdnsChuyenhsId) {
        this.ttcmsdvsdnsChuyenhsId = ttcmsdvsdnsChuyenhsId;
    }
    public TblUsers getTblUsersByUsersChuyenId() {
        return this.tblUsersByUsersChuyenId;
    }
    
    public void setTblUsersByUsersChuyenId(TblUsers tblUsersByUsersChuyenId) {
        this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
    }
    public TblUsers getTblUsersByUsersNhanId() {
        return this.tblUsersByUsersNhanId;
    }
    
    public void setTblUsersByUsersNhanId(TblUsers tblUsersByUsersNhanId) {
        this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
    }
    public TblTtcmsdvsdns getTblTtcmsdvsdns() {
        return this.tblTtcmsdvsdns;
    }
    
    public void setTblTtcmsdvsdns(TblTtcmsdvsdns tblTtcmsdvsdns) {
        this.tblTtcmsdvsdns = tblTtcmsdvsdns;
    }
    public Date getNgayChuyen() {
        return this.ngayChuyen;
    }
    
    public void setNgayChuyen(Date ngayChuyen) {
        this.ngayChuyen = ngayChuyen;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


