package vn.softech.hibernate;
// Generated Feb 3, 2012 4:30:21 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblTthcDm generated by hbm2java
 */
public class TblTthcDm  implements java.io.Serializable {


     private Long tthcDmId;
     private String name;
     private Date created;
     private Date modified;
     private byte status;
     private boolean selected;
     private int usersId;
     private List<TblTthc> tblTthcs = new ArrayList<TblTthc>();

    public TblTthcDm() {
    }

	
    public TblTthcDm(String name, Date created, Date modified, byte status, boolean selected, int usersId) {
        this.name = name;
        this.created = created;
        this.modified = modified;
        this.status = status;
        this.selected = selected;
        this.usersId = usersId;
    }
    public TblTthcDm(String name, Date created, Date modified, byte status, boolean selected, int usersId, List<TblTthc> tblTthcs) {
       this.name = name;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.selected = selected;
       this.usersId = usersId;
       this.tblTthcs = tblTthcs;
    }
   
    public Long getTthcDmId() {
        return this.tthcDmId;
    }
    
    public void setTthcDmId(Long tthcDmId) {
        this.tthcDmId = tthcDmId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public boolean isSelected() {
        return this.selected;
    }
    
    public void setSelected(boolean selected) {
        this.selected = selected;
    }
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }
    public List<TblTthc> getTblTthcs() {
        return this.tblTthcs;
    }
    
    public void setTblTthcs(List<TblTthc> tblTthcs) {
        this.tblTthcs = tblTthcs;
    }




}


