package vn.softech.hibernate;
// Generated Feb 28, 2012 9:43:33 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtcmsdvsdnsButPhe generated by hbm2java
 */
public class TblTtcmsdvsdnsButPhe  implements java.io.Serializable {


     private Long ttcmsdvsdnsButPheId;
     private TblUsers tblUsers;
     private TblTtcmsdvsdns tblTtcmsdvsdns;
     private String noiDung;
     private Date created;
     private Date modified;
     private byte status;

    public TblTtcmsdvsdnsButPhe() {
    }

    public TblTtcmsdvsdnsButPhe(TblUsers tblUsers, TblTtcmsdvsdns tblTtcmsdvsdns, String noiDung, Date created, Date modified, byte status) {
       this.tblUsers = tblUsers;
       this.tblTtcmsdvsdns = tblTtcmsdvsdns;
       this.noiDung = noiDung;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getTtcmsdvsdnsButPheId() {
        return this.ttcmsdvsdnsButPheId;
    }
    
    public void setTtcmsdvsdnsButPheId(Long ttcmsdvsdnsButPheId) {
        this.ttcmsdvsdnsButPheId = ttcmsdvsdnsButPheId;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public TblTtcmsdvsdns getTblTtcmsdvsdns() {
        return this.tblTtcmsdvsdns;
    }
    
    public void setTblTtcmsdvsdns(TblTtcmsdvsdns tblTtcmsdvsdns) {
        this.tblTtcmsdvsdns = tblTtcmsdvsdns;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


