package vn.softech.hibernate;
// Generated Jan 18, 2012 3:03:09 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblThongBao generated by hbm2java
 */
public class TblThongBao  implements java.io.Serializable {


     private Long thongBaoId;
     private String title;
     private String content;
     private Date created;
     private Date modified;
     private byte status;
     private boolean active;
     private Date tuNgay;
     private Date denNgay;
     private int usersId;

    public TblThongBao() {
    }

    public TblThongBao(String title, String content, Date created, Date modified, byte status, boolean active, int usersId) {
       this.title = title;
       this.content = content;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.active = active;
       this.usersId = usersId;
    }
   
    public Long getThongBaoId() {
        return this.thongBaoId;
    }
    
    public void setThongBaoId(Long thongBaoId) {
        this.thongBaoId = thongBaoId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }

	public Date getTuNgay() {
		return tuNgay;
	}

	public void setTuNgay(Date tuNgay) {
		this.tuNgay = tuNgay;
	}

	public Date getDenNgay() {
		return denNgay;
	}

	public void setDenNgay(Date denNgay) {
		this.denNgay = denNgay;
	}




}


