package vn.softech.hibernate;
// Generated Feb 27, 2012 10:59:38 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtpapbdtnsDinhKem generated by hbm2java
 */
public class TblTtpapbdtnsDinhKem  implements java.io.Serializable {


     private Long ttpapbdtnsDinhKemId;
     private TblUsers tblUsers;
     private TblDocument tblDocument;
     private TblTtpapbdtns tblTtpapbdtns;
     private String tenHoSo;
     private Date created;
     private Date modified;
     private byte status;

    public TblTtpapbdtnsDinhKem() {
    }

	
    public TblTtpapbdtnsDinhKem(TblDocument tblDocument, TblTtpapbdtns tblTtpapbdtns, String tenHoSo, Date created, Date modified, byte status) {
        this.tblDocument = tblDocument;
        this.tblTtpapbdtns = tblTtpapbdtns;
        this.tenHoSo = tenHoSo;
        this.created = created;
        this.modified = modified;
        this.status = status;
    }
    public TblTtpapbdtnsDinhKem(TblUsers tblUsers, TblDocument tblDocument, TblTtpapbdtns tblTtpapbdtns, String tenHoSo, Date created, Date modified, byte status) {
       this.tblUsers = tblUsers;
       this.tblDocument = tblDocument;
       this.tblTtpapbdtns = tblTtpapbdtns;
       this.tenHoSo = tenHoSo;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getTtpapbdtnsDinhKemId() {
        return this.ttpapbdtnsDinhKemId;
    }
    
    public void setTtpapbdtnsDinhKemId(Long ttpapbdtnsDinhKemId) {
        this.ttpapbdtnsDinhKemId = ttpapbdtnsDinhKemId;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public TblDocument getTblDocument() {
        return this.tblDocument;
    }
    
    public void setTblDocument(TblDocument tblDocument) {
        this.tblDocument = tblDocument;
    }
    public TblTtpapbdtns getTblTtpapbdtns() {
        return this.tblTtpapbdtns;
    }
    
    public void setTblTtpapbdtns(TblTtpapbdtns tblTtpapbdtns) {
        this.tblTtpapbdtns = tblTtpapbdtns;
    }
    public String getTenHoSo() {
        return this.tenHoSo;
    }
    
    public void setTenHoSo(String tenHoSo) {
        this.tenHoSo = tenHoSo;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


