package vn.softech.hibernate;
// Generated Feb 28, 2012 9:43:33 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtcmsdvsdnsDinhKem generated by hbm2java
 */
public class TblTtcmsdvsdnsDinhKem  implements java.io.Serializable {


     private Long ttcmsdvsdnsDinhKemId;
     private TblUsers tblUsers;
     private TblDocument tblDocument;
     private TblTtcmsdvsdns tblTtcmsdvsdns;
     private String tenHoSo;
     private Date created;
     private Date modified;
     private byte status;

    public TblTtcmsdvsdnsDinhKem() {
    }

	
    public TblTtcmsdvsdnsDinhKem(TblDocument tblDocument, TblTtcmsdvsdns tblTtcmsdvsdns, String tenHoSo, Date created, Date modified, byte status) {
        this.tblDocument = tblDocument;
        this.tblTtcmsdvsdns = tblTtcmsdvsdns;
        this.tenHoSo = tenHoSo;
        this.created = created;
        this.modified = modified;
        this.status = status;
    }
    public TblTtcmsdvsdnsDinhKem(TblUsers tblUsers, TblDocument tblDocument, TblTtcmsdvsdns tblTtcmsdvsdns, String tenHoSo, Date created, Date modified, byte status) {
       this.tblUsers = tblUsers;
       this.tblDocument = tblDocument;
       this.tblTtcmsdvsdns = tblTtcmsdvsdns;
       this.tenHoSo = tenHoSo;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getTtcmsdvsdnsDinhKemId() {
        return this.ttcmsdvsdnsDinhKemId;
    }
    
    public void setTtcmsdvsdnsDinhKemId(Long ttcmsdvsdnsDinhKemId) {
        this.ttcmsdvsdnsDinhKemId = ttcmsdvsdnsDinhKemId;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public TblDocument getTblDocument() {
        return this.tblDocument;
    }
    
    public void setTblDocument(TblDocument tblDocument) {
        this.tblDocument = tblDocument;
    }
    public TblTtcmsdvsdns getTblTtcmsdvsdns() {
        return this.tblTtcmsdvsdns;
    }
    
    public void setTblTtcmsdvsdns(TblTtcmsdvsdns tblTtcmsdvsdns) {
        this.tblTtcmsdvsdns = tblTtcmsdvsdns;
    }
    public String getTenHoSo() {
        return this.tenHoSo;
    }
    
    public void setTenHoSo(String tenHoSo) {
        this.tenHoSo = tenHoSo;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


