package vn.softech.hibernate;
// Generated Feb 3, 2012 4:17:59 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblUrls generated by hbm2java
 */
public class TblUrls  implements java.io.Serializable {


     private Long urlsId;
     private Long parentId;
     private String name;
     private Byte priority;
     private String link;
     private Boolean active;
     private Boolean popup;
     private String icon;
     private List<TblUrlsGroups> tblUrlsGroupses = new ArrayList<TblUrlsGroups>();

    public TblUrls() {
    }

	
    public TblUrls(String name) {
        this.name = name;
    }
    public TblUrls(Long parentId, String name, Byte priority, String link, Boolean active, Boolean popup, String icon, List<TblUrlsGroups> tblUrlsGroupses) {
       this.parentId = parentId;
       this.name = name;
       this.priority = priority;
       this.link = link;
       this.active = active;
       this.popup = popup;
       this.icon = icon;
       this.tblUrlsGroupses = tblUrlsGroupses;
    }
   
    public Long getUrlsId() {
        return this.urlsId;
    }
    
    public void setUrlsId(Long urlsId) {
        this.urlsId = urlsId;
    }
    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Byte getPriority() {
        return this.priority;
    }
    
    public void setPriority(Byte priority) {
        this.priority = priority;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Boolean getPopup() {
        return this.popup;
    }
    
    public void setPopup(Boolean popup) {
        this.popup = popup;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public List<TblUrlsGroups> getTblUrlsGroupses() {
        return this.tblUrlsGroupses;
    }
    
    public void setTblUrlsGroupses(List<TblUrlsGroups> tblUrlsGroupses) {
        this.tblUrlsGroupses = tblUrlsGroupses;
    }




}


