package vn.softech.hibernate;
// Generated Feb 3, 2012 4:17:59 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblUsersGroups generated by hbm2java
 */
public class TblUsersGroups  implements java.io.Serializable {


     private TblUsersGroupsId id;
     private TblGroups tblGroups;
     private TblUsers tblUsers;
     private Date created;
     private Date modified;
     private Byte status;

    public TblUsersGroups() {
    }

	
    public TblUsersGroups(TblUsersGroupsId id, TblGroups tblGroups, TblUsers tblUsers, Date created, Date modified) {
        this.id = id;
        this.tblGroups = tblGroups;
        this.tblUsers = tblUsers;
        this.created = created;
        this.modified = modified;
    }
    public TblUsersGroups(TblUsersGroupsId id, TblGroups tblGroups, TblUsers tblUsers, Date created, Date modified, Byte status) {
       this.id = id;
       this.tblGroups = tblGroups;
       this.tblUsers = tblUsers;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public TblUsersGroupsId getId() {
        return this.id;
    }
    
    public void setId(TblUsersGroupsId id) {
        this.id = id;
    }
    public TblGroups getTblGroups() {
        return this.tblGroups;
    }
    
    public void setTblGroups(TblGroups tblGroups) {
        this.tblGroups = tblGroups;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


