package vn.softech.hibernate;
// Generated Feb 3, 2012 4:17:59 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblUrlsGroups generated by hbm2java
 */
public class TblUrlsGroups  implements java.io.Serializable {

     private TblUrlsGroupsId id;
     private TblGroups tblGroups;
     private TblUrls tblUrls;
     private Date created;
     private Date modified;
     private Byte status;

    public TblUrlsGroups() {
    }

	
    public TblUrlsGroups(TblUrlsGroupsId id, TblGroups tblGroups, TblUrls tblUrls, Date created, Date modified) {
        this.id = id;
        this.tblGroups = tblGroups;
        this.tblUrls = tblUrls;
        this.created = created;
        this.modified = modified;
    }
    public TblUrlsGroups(TblUrlsGroupsId id, TblGroups tblGroups, TblUrls tblUrls, Date created, Date modified, Byte status) {
       this.id = id;
       this.tblGroups = tblGroups;
       this.tblUrls = tblUrls;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public TblUrlsGroupsId getId() {
        return this.id;
    }
    
    public void setId(TblUrlsGroupsId id) {
        this.id = id;
    }
    public TblGroups getTblGroups() {
        return this.tblGroups;
    }
    
    public void setTblGroups(TblGroups tblGroups) {
        this.tblGroups = tblGroups;
    }
    public TblUrls getTblUrls() {
        return this.tblUrls;
    }
    
    public void setTblUrls(TblUrls tblUrls) {
        this.tblUrls = tblUrls;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


