package vn.softech.hibernate;
// Generated Jan 6, 2012 3:11:47 PM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblVote generated by hbm2java
 */
public class TblVote  implements java.io.Serializable {


     private Long voteId;
     private String content;
     private Date created;
     private Date modified;
     private Long status;
     private boolean active;
     private List<TblVoteItem> voteItems = new ArrayList<TblVoteItem>();

    public TblVote() {
    }

	
    public TblVote(String content, Date created, Date modified, Long status, boolean active) {
        this.content = content;
        this.created = created;
        this.modified = modified;
        this.status = status;
        this.active = active;
    }
    public TblVote(String content, Date created, Date modified, Long status, boolean active, List<TblVoteItem> tblVoteItems) {
       this.content = content;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.active = active;
       this.setVoteItems(tblVoteItems);
    }
   
    public Long getVoteId() {
        return this.voteId;
    }
    
    public void setVoteId(Long voteId) {
        this.voteId = voteId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Long isStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

	public List<TblVoteItem> getVoteItems() {
		return voteItems;
	}


	public void setVoteItems(List<TblVoteItem> voteItems) {
		this.voteItems = voteItems;
	}




}


