package vn.softech.hibernate;
// Generated Mar 14, 2012 8:28:15 AM by Hibernate Tools 3.4.0.CR1



/**
 * TblXaPhuong generated by hbm2java
 */
public class TblXaPhuong  implements java.io.Serializable {


     private Long xaPhuongId;
     private TblQuanHuyen tblQuanHuyen;
     private String tenXaPhuong;
     private Boolean isTrungTam;
     private Byte status;

    public TblXaPhuong() {
    }

	
    public TblXaPhuong(String tenXaPhuong) {
        this.tenXaPhuong = tenXaPhuong;
    }
    public TblXaPhuong(TblQuanHuyen tblQuanHuyen, String tenXaPhuong, Boolean isTrungTam, Byte status) {
       this.tblQuanHuyen = tblQuanHuyen;
       this.tenXaPhuong = tenXaPhuong;
       this.isTrungTam = isTrungTam;
       this.status = status;
    }
   
    public Long getXaPhuongId() {
        return this.xaPhuongId;
    }
    
    public void setXaPhuongId(Long xaPhuongId) {
        this.xaPhuongId = xaPhuongId;
    }
    public TblQuanHuyen getTblQuanHuyen() {
        return this.tblQuanHuyen;
    }
    
    public void setTblQuanHuyen(TblQuanHuyen tblQuanHuyen) {
        this.tblQuanHuyen = tblQuanHuyen;
    }
    public String getTenXaPhuong() {
        return this.tenXaPhuong;
    }
    
    public void setTenXaPhuong(String tenXaPhuong) {
        this.tenXaPhuong = tenXaPhuong;
    }
    public Boolean getIsTrungTam() {
        return this.isTrungTam;
    }
    
    public void setIsTrungTam(Boolean isTrungTam) {
        this.isTrungTam = isTrungTam;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


