package vn.softech.hibernate;
// Generated Feb 8, 2012 8:08:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblAdvert generated by hbm2java
 */
public class TblAdvert  implements java.io.Serializable {


     private Long advertId;
     private String name;
     private Byte priority;
     private Byte status;
     private String link;
     private String pathImage;
     private Byte position;
     private Date exprire;
     private String fileType;
     private Date created;
     private Date modified;
     private long usersId;

    public TblAdvert() {
    }

	
    public TblAdvert(String name, String link, String pathImage, Date exprire, String fileType, Date created, Date modified, long usersId) {
        this.name = name;
        this.link = link;
        this.pathImage = pathImage;
        this.exprire = exprire;
        this.fileType = fileType;
        this.created = created;
        this.modified = modified;
        this.usersId = usersId;
    }
    public TblAdvert(String name, Byte priority, Byte status, String link, String pathImage, Byte position, Date exprire, String fileType, Date created, Date modified, long usersId) {
       this.name = name;
       this.priority = priority;
       this.status = status;
       this.link = link;
       this.pathImage = pathImage;
       this.position = position;
       this.exprire = exprire;
       this.fileType = fileType;
       this.created = created;
       this.modified = modified;
       this.usersId = usersId;
    }
   
    public Long getAdvertId() {
        return this.advertId;
    }
    
    public void setAdvertId(Long advertId) {
        this.advertId = advertId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Byte getPriority() {
        return this.priority;
    }
    
    public void setPriority(Byte priority) {
        this.priority = priority;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getPathImage() {
        return this.pathImage;
    }
    
    public void setPathImage(String pathImage) {
        this.pathImage = pathImage;
    }
    public Byte getPosition() {
        return this.position;
    }
    
    public void setPosition(Byte position) {
        this.position = position;
    }
    public Date getExprire() {
        return this.exprire;
    }
    
    public void setExprire(Date exprire) {
        this.exprire = exprire;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public long getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(long usersId) {
        this.usersId = usersId;
    }




}


