package vn.softech.hibernate;
// Generated Feb 18, 2012 8:30:00 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblBmdt generated by hbm2java
 */
public class TblBmdt  implements java.io.Serializable {


     private Long bmdtId;
     private TblBmdtDm tblBmdtDm;
     private TblUsers tblUsers;
     private String description;
     private Boolean active;
     private byte priority;
     private byte status;
     private byte[] data;
     private String fileName;
     private Date created;
     private Date modified;
     private long usersId;

    public TblBmdt() {
    }

    public TblBmdt(TblBmdtDm tblBmdtDm, String description, byte priority, byte status, byte[] data, String fileName, Date created, Date modified, long usersId, TblUsers tblUsers) {
       this.tblBmdtDm = tblBmdtDm;
       this.tblUsers = tblUsers;
       this.description = description;
       this.priority = priority;
       this.status = status;
       this.data = data;
       this.fileName = fileName;
       this.created = created;
       this.modified = modified;
       this.usersId = usersId;
    }
   
    public Long getBmdtId() {
        return this.bmdtId;
    }
    
    public void setBmdtId(Long bmdtId) {
        this.bmdtId = bmdtId;
    }
    public TblBmdtDm getTblBmdtDm() {
        return this.tblBmdtDm;
    }
    
    public void setTblBmdtDm(TblBmdtDm tblBmdtDm) {
        this.tblBmdtDm = tblBmdtDm;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getPriority() {
        return this.priority;
    }
    
    public void setPriority(byte priority) {
        this.priority = priority;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public long getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(long usersId) {
        this.usersId = usersId;
    }

	public TblUsers getTblUsers() {
		return tblUsers;
	}

	public void setTblUsers(TblUsers tblUsers) {
		this.tblUsers = tblUsers;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}




}


