package vn.softech.hibernate;

// Generated Apr 23, 2012 5:48:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblCktc generated by hbm2java
 */
public class TblCktc implements java.io.Serializable {

	private Long cktcId;
	private TblCktcCm tblCktcCm;
	private String tieuDe;
	private String noiDung;
	private Date created;
	private Date modified;
	private Date ngayPd;
	private Byte status;

	public TblCktc() {
	}

	public TblCktc(TblCktcCm tblCktcCm, String tieuDe, String noiDung,
			Date created, Date modified, Date ngayPd, Byte status) {
		this.tblCktcCm = tblCktcCm;
		this.tieuDe = tieuDe;
		this.noiDung = noiDung;
		this.created = created;
		this.modified = modified;
		this.ngayPd = ngayPd;
		this.status = status;
	}

	public Long getCktcId() {
		return this.cktcId;
	}

	public void setCktcId(Long cktcId) {
		this.cktcId = cktcId;
	}

	public TblCktcCm getTblCktcCm() {
		return this.tblCktcCm;
	}

	public void setTblCktcCm(TblCktcCm tblCktcCm) {
		this.tblCktcCm = tblCktcCm;
	}

	public String getTieuDe() {
		return this.tieuDe;
	}

	public void setTieuDe(String tieuDe) {
		this.tieuDe = tieuDe;
	}

	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public Date getNgayPd() {
		return this.ngayPd;
	}

	public void setNgayPd(Date ngayPd) {
		this.ngayPd = ngayPd;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
