package vn.softech.hibernate;
// Generated Feb 8, 2012 8:08:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblLink generated by hbm2java
 */
public class TblLink  implements java.io.Serializable {


     private Long linkId;
     private String name;
     private String href;
     private String description;
     private Date created;
     private Date modified;
     private Byte status;

    public TblLink() {
    }

	
    public TblLink(String name, String href, String description, Date created, Date modified) {
        this.name = name;
        this.href = href;
        this.description = description;
        this.created = created;
        this.modified = modified;
    }
    public TblLink(String name, String href, String description, Date created, Date modified, Byte status) {
       this.name = name;
       this.href = href;
       this.description = description;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getLinkId() {
        return this.linkId;
    }
    
    public void setLinkId(Long linkId) {
        this.linkId = linkId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getHref() {
        return this.href;
    }
    
    public void setHref(String href) {
        this.href = href;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


