package vn.softech.hibernate;
// Generated Jan 18, 2012 3:03:09 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblLegalDocuments generated by hbm2java
 */
public class TblLegalDocuments  implements java.io.Serializable {


     private Long legalDocumentsId;
     private TblLdLoaiVb tblLdLoaiVb;
     private TblLdCoQuan tblLdCoQuan;
     private TblLdLinhVuc tblLdLinhVuc;
     private String tenVb;
     private String soHieuVb;
     private String fileName;
     private String fileType;
     private byte[] data;
     private Date ngayBh;
     private Date ngayHieuLuc;
     private String nguoiKyVb;
     private String filePath;
     private byte status;
     private Date created;
     private Date modified;
     private Integer usersId;

    public TblLegalDocuments() {
    }

	
    public TblLegalDocuments(TblLdLoaiVb tblLdLoaiVb, TblLdCoQuan tblLdCoQuan, TblLdLinhVuc tblLdLinhVuc, String tenVb, String soHieuVb, String fileName, byte[] data, Date ngayBh, Date ngayHieuLuc, String nguoiKyVb, byte status, Date created, Date modified) {
        this.tblLdLoaiVb = tblLdLoaiVb;
        this.tblLdCoQuan = tblLdCoQuan;
        this.tblLdLinhVuc = tblLdLinhVuc;
        this.tenVb = tenVb;
        this.soHieuVb = soHieuVb;
        this.fileName = fileName;
        this.data = data;
        this.ngayBh = ngayBh;
        this.ngayHieuLuc = ngayHieuLuc;
        this.nguoiKyVb = nguoiKyVb;
        this.status = status;
        this.created = created;
        this.modified = modified;
    }
    public TblLegalDocuments(TblLdLoaiVb tblLdLoaiVb, TblLdCoQuan tblLdCoQuan, TblLdLinhVuc tblLdLinhVuc, String tenVb, String soHieuVb, String fileName, String fileType, byte[] data, Date ngayBh, Date ngayHieuLuc, String nguoiKyVb, byte status, Date created, Date modified, Integer usersId) {
       this.tblLdLoaiVb = tblLdLoaiVb;
       this.tblLdCoQuan = tblLdCoQuan;
       this.tblLdLinhVuc = tblLdLinhVuc;
       this.tenVb = tenVb;
       this.soHieuVb = soHieuVb;
       this.fileName = fileName;
       this.fileType = fileType;
       this.data = data;
       this.ngayBh = ngayBh;
       this.ngayHieuLuc = ngayHieuLuc;
       this.nguoiKyVb = nguoiKyVb;
       this.status = status;
       this.created = created;
       this.modified = modified;
       this.usersId = usersId;
    }
   
    public Long getLegalDocumentsId() {
        return this.legalDocumentsId;
    }
    
    public void setLegalDocumentsId(Long legalDocumentsId) {
        this.legalDocumentsId = legalDocumentsId;
    }
    public TblLdLoaiVb getTblLdLoaiVb() {
        return this.tblLdLoaiVb;
    }
    
    public void setTblLdLoaiVb(TblLdLoaiVb tblLdLoaiVb) {
        this.tblLdLoaiVb = tblLdLoaiVb;
    }
    public TblLdCoQuan getTblLdCoQuan() {
        return this.tblLdCoQuan;
    }
    
    public void setTblLdCoQuan(TblLdCoQuan tblLdCoQuan) {
        this.tblLdCoQuan = tblLdCoQuan;
    }
    public TblLdLinhVuc getTblLdLinhVuc() {
        return this.tblLdLinhVuc;
    }
    
    public void setTblLdLinhVuc(TblLdLinhVuc tblLdLinhVuc) {
        this.tblLdLinhVuc = tblLdLinhVuc;
    }
    public String getTenVb() {
        return this.tenVb;
    }
    
    public void setTenVb(String tenVb) {
        this.tenVb = tenVb;
    }
    public String getSoHieuVb() {
        return this.soHieuVb;
    }
    
    public void setSoHieuVb(String soHieuVb) {
        this.soHieuVb = soHieuVb;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }
    public Date getNgayBh() {
        return this.ngayBh;
    }
    
    public void setNgayBh(Date ngayBh) {
        this.ngayBh = ngayBh;
    }
    public Date getNgayHieuLuc() {
        return this.ngayHieuLuc;
    }
    
    public void setNgayHieuLuc(Date ngayHieuLuc) {
        this.ngayHieuLuc = ngayHieuLuc;
    }
    public String getNguoiKyVb() {
        return this.nguoiKyVb;
    }
    
    public void setNguoiKyVb(String nguoiKyVb) {
        this.nguoiKyVb = nguoiKyVb;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Integer getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }


	public String getFilePath() {
		return filePath;
	}


	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}
}


