package vn.softech.hibernate;
// Generated Feb 27, 2012 10:59:38 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblPhongBan generated by hbm2java
 */
public class TblPhongBan  implements java.io.Serializable {


     private Long phongBanId;
     private String tenPhongBan;
     private Date created;
     private Date modified;
     private byte status;

    public TblPhongBan() {
    }

    public TblPhongBan(String tenPhongBan, Date created, Date modified, byte status) {
       this.tenPhongBan = tenPhongBan;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getPhongBanId() {
        return this.phongBanId;
    }
    
    public void setPhongBanId(Long phongBanId) {
        this.phongBanId = phongBanId;
    }
    public String getTenPhongBan() {
        return this.tenPhongBan;
    }
    
    public void setTenPhongBan(String tenPhongBan) {
        this.tenPhongBan = tenPhongBan;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


