package vn.softech.hibernate;
// Generated Feb 17, 2012 3:49:07 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblQuestion generated by hbm2java
 */
public class TblQuestion  implements java.io.Serializable {
	
     private Long questionId;
     private String title;
     private String name;
     private String address;
     private String email;
     private String question;
     private byte status;
     private Date created;
     private Date modified;
     private List<TblAnswer> tblAnswers = new ArrayList<TblAnswer>();
     private List<TblQuestionAssign> tblQuestionAssigns = new ArrayList<TblQuestionAssign>();

    public TblQuestion() {
    }

	
    public TblQuestion(String title, String name, String address, String email, String question, byte status, Date created, Date modified) {
        this.title = title;
        this.name = name;
        this.address = address;
        this.email = email;
        this.question = question;
        this.status = status;
        this.created = created;
        this.modified = modified;
    }
    public TblQuestion(String title, String name, String address, String email, String question, byte status, Date created, Date modified, List<TblAnswer> tblAnswers, List<TblQuestionAssign> tblQuestionAssigns) {
       this.title = title;
       this.name = name;
       this.address = address;
       this.email = email;
       this.question = question;
       this.status = status;
       this.created = created;
       this.modified = modified;
       this.tblAnswers = tblAnswers;
       this.tblQuestionAssigns = tblQuestionAssigns;
    }
   
    public Long getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public List<TblAnswer> getTblAnswers() {
        return this.tblAnswers;
    }
    
    public void setTblAnswers(List<TblAnswer> tblAnswers) {
        this.tblAnswers = tblAnswers;
    }
    public List<TblQuestionAssign> getTblQuestionAssigns() {
        return this.tblQuestionAssigns;
    }
    
    public void setTblQuestionAssigns(List<TblQuestionAssign> tblQuestionAssigns) {
        this.tblQuestionAssigns = tblQuestionAssigns;
    }
}


