package vn.softech.hibernate;

// Generated Jul 18, 2012 2:23:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblSuKienTinTuc generated by hbm2java
 */
public class TblSuKienTinTuc implements java.io.Serializable {

	private Long suKienTinTucId;
	private long suKienId;
	private String title;
	private String summary;
	private String content;
	private String pathImage;
	private Date created;
	private Date modified;
	private boolean active;
	private byte status;

	public TblSuKienTinTuc() {
	}

	public TblSuKienTinTuc(long suKienId, String title, String summary,
			String content, String pathImage, Date created, Date modified,
			boolean active, byte status) {
		this.suKienId = suKienId;
		this.title = title;
		this.summary = summary;
		this.content = content;
		this.pathImage = pathImage;
		this.created = created;
		this.modified = modified;
		this.active = active;
		this.status = status;
	}

	public Long getSuKienTinTucId() {
		return this.suKienTinTucId;
	}

	public void setSuKienTinTucId(Long suKienTinTucId) {
		this.suKienTinTucId = suKienTinTucId;
	}

	public long getSuKienId() {
		return this.suKienId;
	}

	public void setSuKienId(long suKienId) {
		this.suKienId = suKienId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPathImage() {
		return this.pathImage;
	}

	public void setPathImage(String pathImage) {
		this.pathImage = pathImage;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
