package vn.softech.hibernate;

// Generated Jul 18, 2012 2:23:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblSuKien generated by hbm2java
 */
public class TblSuKien implements java.io.Serializable {

	private Long suKienId;
	private String name;
	private boolean active;
	private String pathImage;
	private Date created;
	private Date modified;
	private byte status;

	public TblSuKien() {
	}

	public TblSuKien(String name, boolean active, Date created, Date modified,
			byte status) {
		this.name = name;
		this.active = active;
		this.created = created;
		this.modified = modified;
		this.status = status;
	}

	public Long getSuKienId() {
		return this.suKienId;
	}

	public void setSuKienId(Long suKienId) {
		this.suKienId = suKienId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public String getPathImage() {
		return pathImage;
	}

	public void setPathImage(String pathImage) {
		this.pathImage = pathImage;
	}

}
