package vn.softech.hibernate;
// Generated Feb 3, 2012 1:51:40 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTinTuc generated by hbm2java
 */
public class TblTinTuc  implements java.io.Serializable {

     private Long tinTucId;
     private TblChuyenMuc tblChuyenMuc;
     private String title;
     private String summary;
     private String content;
     private String pathImage;
     private Date created;
     private Date modified;
     private byte status;
     private byte active;
     private byte approved;
     private Boolean hot;
     private TblUsers usersCreater;
     private TblUsers usersApprover;
     private Boolean isTinbenngoai;
     private String urlSource;
     
    public TblTinTuc() {
    }
   
    public Long getTinTucId() {
        return this.tinTucId;
    }
    
    public void setTinTucId(Long tinTucId) {
        this.tinTucId = tinTucId;
    }
    public TblChuyenMuc getTblChuyenMuc() {
        return this.tblChuyenMuc;
    }
    
    public void setTblChuyenMuc(TblChuyenMuc tblChuyenMuc) {
        this.tblChuyenMuc = tblChuyenMuc;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getPathImage() {
        return this.pathImage;
    }
    
    public void setPathImage(String pathImage) {
        this.pathImage = pathImage;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte b) {
        this.status = b;
    }
    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte b) {
        this.active = b;
    }
    public byte getApproved() {
        return this.approved;
    }
    
    public void setApproved(byte approved) {
        this.approved = approved;
    }
    public Boolean getHot() {
        return this.hot;
    }
    
    public void setHot(Boolean hot) {
        this.hot = hot;
    }

	public Boolean getIsTinbenngoai() {
		return isTinbenngoai;
	}


	public void setIsTinbenngoai(Boolean isTinbenngoai) {
		this.isTinbenngoai = isTinbenngoai;
	}


	public String getUrlSource() {
		return urlSource;
	}


	public void setUrlSource(String urlSource) {
		this.urlSource = urlSource;
	}

	public TblUsers getUsersCreater() {
		return usersCreater;
	}

	public void setUsersCreater(TblUsers usersCreater) {
		this.usersCreater = usersCreater;
	}

	public TblUsers getUsersApprover() {
		return usersApprover;
	}

	public void setUsersApprover(TblUsers usersApprover) {
		this.usersApprover = usersApprover;
	}




}


