package vn.softech.hibernate;
// Generated Feb 27, 2012 10:59:38 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtcgcndkmsxdcbButPhe generated by hbm2java
 */
public class TblTtcgcndkmsxdcbButPhe  implements java.io.Serializable {


     private Long ttcgcndkmsxdcbButPheId;
     private TblTtcgcndkmsxdcb tblTtcgcndkmsxdcb;
     private TblUsers tblUsers;
     private String noiDung;
     private Date created;
     private Date modified;
     private byte status;

    public TblTtcgcndkmsxdcbButPhe() {
    }

    public TblTtcgcndkmsxdcbButPhe(TblTtcgcndkmsxdcb tblTtcgcndkmsxdcb, TblUsers tblUsers, String noiDung, Date created, Date modified, byte status) {
       this.tblTtcgcndkmsxdcb = tblTtcgcndkmsxdcb;
       this.tblUsers = tblUsers;
       this.noiDung = noiDung;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getTtcgcndkmsxdcbButPheId() {
        return this.ttcgcndkmsxdcbButPheId;
    }
    
    public void setTtcgcndkmsxdcbButPheId(Long ttcgcndkmsxdcbButPheId) {
        this.ttcgcndkmsxdcbButPheId = ttcgcndkmsxdcbButPheId;
    }
    public TblTtcgcndkmsxdcb getTblTtcgcndkmsxdcb() {
        return this.tblTtcgcndkmsxdcb;
    }
    
    public void setTblTtcgcndkmsxdcb(TblTtcgcndkmsxdcb tblTtcgcndkmsxdcb) {
        this.tblTtcgcndkmsxdcb = tblTtcgcndkmsxdcb;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


