package vn.softech.hibernate;
// Generated Feb 27, 2012 10:59:38 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtpdgmstsButPhe generated by hbm2java
 */
public class TblTtpdgmstsButPhe  implements java.io.Serializable {


     private Long ttpdgmstsButPheId;
     private TblUsers tblUsers;
     private TblTtpdgmsts tblTtpdgmsts;
     private String noiDung;
     private Date created;
     private Date modified;
     private byte status;

    public TblTtpdgmstsButPhe() {
    }

    public TblTtpdgmstsButPhe(TblUsers tblUsers, TblTtpdgmsts tblTtpdgmsts, String noiDung, Date created, Date modified, byte status) {
       this.tblUsers = tblUsers;
       this.tblTtpdgmsts = tblTtpdgmsts;
       this.noiDung = noiDung;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getTtpdgmstsButPheId() {
        return this.ttpdgmstsButPheId;
    }
    
    public void setTtpdgmstsButPheId(Long ttpdgmstsButPheId) {
        this.ttpdgmstsButPheId = ttpdgmstsButPheId;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public TblTtpdgmsts getTblTtpdgmsts() {
        return this.tblTtpdgmsts;
    }
    
    public void setTblTtpdgmsts(TblTtpdgmsts tblTtpdgmsts) {
        this.tblTtpdgmsts = tblTtpdgmsts;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


