package vn.softech.hibernate;
// Generated Mar 24, 2012 3:21:23 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtpdgmstsChuyenhs generated by hbm2java
 */
public class TblTtpdgmstsChuyenhs  implements java.io.Serializable {


     private Long ttpdgmstsChuyenhsId;
     private TblUsers tblUsersByUsersChuyenId;
     private TblUsers tblUsersByUsersNhanId;
     private TblTtpdgmsts tblTtpdgmsts;
     private Date ngayChuyen;
     private String ghiChu;
     private Byte status;

    public TblTtpdgmstsChuyenhs() {
    }

	
    public TblTtpdgmstsChuyenhs(TblUsers tblUsersByUsersChuyenId, TblUsers tblUsersByUsersNhanId, TblTtpdgmsts tblTtpdgmsts, Date ngayChuyen) {
        this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
        this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
        this.tblTtpdgmsts = tblTtpdgmsts;
        this.ngayChuyen = ngayChuyen;
    }
    public TblTtpdgmstsChuyenhs(TblUsers tblUsersByUsersChuyenId, TblUsers tblUsersByUsersNhanId, TblTtpdgmsts tblTtpdgmsts, Date ngayChuyen, String ghiChu, Byte status) {
       this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
       this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
       this.tblTtpdgmsts = tblTtpdgmsts;
       this.ngayChuyen = ngayChuyen;
       this.ghiChu = ghiChu;
       this.status = status;
    }
   
    public Long getTtpdgmstsChuyenhsId() {
        return this.ttpdgmstsChuyenhsId;
    }
    
    public void setTtpdgmstsChuyenhsId(Long ttpdgmstsChuyenhsId) {
        this.ttpdgmstsChuyenhsId = ttpdgmstsChuyenhsId;
    }
    public TblUsers getTblUsersByUsersChuyenId() {
        return this.tblUsersByUsersChuyenId;
    }
    
    public void setTblUsersByUsersChuyenId(TblUsers tblUsersByUsersChuyenId) {
        this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
    }
    public TblUsers getTblUsersByUsersNhanId() {
        return this.tblUsersByUsersNhanId;
    }
    
    public void setTblUsersByUsersNhanId(TblUsers tblUsersByUsersNhanId) {
        this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
    }
    public TblTtpdgmsts getTblTtpdgmsts() {
        return this.tblTtpdgmsts;
    }
    
    public void setTblTtpdgmsts(TblTtpdgmsts tblTtpdgmsts) {
        this.tblTtpdgmsts = tblTtpdgmsts;
    }
    public Date getNgayChuyen() {
        return this.ngayChuyen;
    }
    
    public void setNgayChuyen(Date ngayChuyen) {
        this.ngayChuyen = ngayChuyen;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


