package vn.softech.hibernate;
// Generated Feb 11, 2012 9:12:01 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTracking generated by hbm2java
 */
public class TblTracking  implements java.io.Serializable {


     private Long trackingId;
     private String url;
     private String ipAddress;
     private Date accessDate;

    public TblTracking() {
    }

    public TblTracking(String url, String ipAddress, Date accessDate) {
       this.url = url;
       this.ipAddress = ipAddress;
       this.accessDate = accessDate;
    }
   
    public Long getTrackingId() {
        return this.trackingId;
    }
    
    public void setTrackingId(Long trackingId) {
        this.trackingId = trackingId;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Date getAccessDate() {
        return this.accessDate;
    }
    
    public void setAccessDate(Date accessDate) {
        this.accessDate = accessDate;
    }




}


