package vn.softech.hibernate;
// Generated Feb 27, 2012 10:59:38 AM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblToChuc generated by hbm2java
 */
public class TblToChuc  implements java.io.Serializable {


     private Long toChucId;
     private String tenCoQuan;
     private String diaChi;
     private String email;
     private String soDienThoai;
     private String soFax;
     private Date created;
     private Date modified;
     private byte status;
     private String tinhThanh;
     private String quanHuyen;
     private String xaPhuong;
     private String maSoDonVi;
     
     private List<TblTtpdgmsts> tblTtpdgmstses = new ArrayList<TblTtpdgmsts>();
     private List<TblTtcgcndkmsxdcb> tblTtcgcndkmsxdcbs = new ArrayList<TblTtcgcndkmsxdcb>();
     private List<TblTtpapbdtns> tblTtpapbdtnses = new ArrayList<TblTtpapbdtns>();
     private List<TblTtcmsdvsdns>  tblTtcmsdvsdnses = new ArrayList<TblTtcmsdvsdns>();
     
    public TblToChuc() {
    }

	
    public TblToChuc(String tenCoQuan, String diaChi, Date created, Date modified, byte status) {
        this.tenCoQuan = tenCoQuan;
        this.diaChi = diaChi;
        this.created = created;
        this.modified = modified;
        this.status = status;
    }
    public TblToChuc(String tenCoQuan, String diaChi, String email, String soDienThoai, String soFax, Date created, Date modified, byte status, List<TblTtpdgmsts> tblTtpdgmstses, List<TblTtcgcndkmsxdcb> tblTtcgcndkmsxdcbs, List<TblTtpapbdtns> tblTtpapbdtnses) {
       this.tenCoQuan = tenCoQuan;
       this.diaChi = diaChi;
       this.email = email;
       this.soDienThoai = soDienThoai;
       this.soFax = soFax;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.tblTtpdgmstses = tblTtpdgmstses;
       this.tblTtcgcndkmsxdcbs = tblTtcgcndkmsxdcbs;
       this.tblTtpapbdtnses = tblTtpapbdtnses;
    }
   
    public Long getToChucId() {
        return this.toChucId;
    }
    
    public void setToChucId(Long toChucId) {
        this.toChucId = toChucId;
    }
    public String getTenCoQuan() {
        return this.tenCoQuan;
    }
    
    public void setTenCoQuan(String tenCoQuan) {
        this.tenCoQuan = tenCoQuan;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public String getSoFax() {
        return this.soFax;
    }
    
    public void setSoFax(String soFax) {
        this.soFax = soFax;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public List<TblTtpdgmsts> getTblTtpdgmstses() {
        return this.tblTtpdgmstses;
    }
    
    public void setTblTtpdgmstses(List<TblTtpdgmsts> tblTtpdgmstses) {
        this.tblTtpdgmstses = tblTtpdgmstses;
    }
    public List<TblTtcgcndkmsxdcb> getTblTtcgcndkmsxdcbs() {
        return this.tblTtcgcndkmsxdcbs;
    }
    
    public void setTblTtcgcndkmsxdcbs(List<TblTtcgcndkmsxdcb> tblTtcgcndkmsxdcbs) {
        this.tblTtcgcndkmsxdcbs = tblTtcgcndkmsxdcbs;
    }
    public List<TblTtpapbdtns> getTblTtpapbdtnses() {
        return this.tblTtpapbdtnses;
    }
    
    public void setTblTtpapbdtnses(List<TblTtpapbdtns> tblTtpapbdtnses) {
        this.tblTtpapbdtnses = tblTtpapbdtnses;
    }


	public List<TblTtcmsdvsdns> getTblTtcmsdvsdnses() {
		return tblTtcmsdvsdnses;
	}


	public void setTblTtcmsdvsdnses(List<TblTtcmsdvsdns> tblTtcmsdvsdnses) {
		this.tblTtcmsdvsdnses = tblTtcmsdvsdnses;
	}


	public String getTinhThanh() {
		return tinhThanh;
	}


	public void setTinhThanh(String tinhThanh) {
		this.tinhThanh = tinhThanh;
	}


	public String getQuanHuyen() {
		return quanHuyen;
	}


	public void setQuanHuyen(String quanHuyen) {
		this.quanHuyen = quanHuyen;
	}


	public String getXaPhuong() {
		return xaPhuong;
	}


	public void setXaPhuong(String xaPhuong) {
		this.xaPhuong = xaPhuong;
	}


	public String getMaSoDonVi() {
		return maSoDonVi;
	}


	public void setMaSoDonVi(String maSoDonVi) {
		this.maSoDonVi = maSoDonVi;
	}




}


