package vn.softech.hibernate;
// Generated Feb 27, 2012 10:59:38 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtpdgmstsDinhKem generated by hbm2java
 */
public class TblTtpdgmstsDinhKem  implements java.io.Serializable {


     private Long ttpdgmstsDinhKemId;
     private TblUsers tblUsers;
     private TblDocument tblDocument;
     private TblTtpdgmsts tblTtpdgmsts;
     private String tenHoSo;
     private Date created;
     private Date modified;
     private byte status;

    public TblTtpdgmstsDinhKem() {
    }

	
    public TblTtpdgmstsDinhKem(TblDocument tblDocument, TblTtpdgmsts tblTtpdgmsts, String tenHoSo, Date created, Date modified, byte status) {
        this.tblDocument = tblDocument;
        this.tblTtpdgmsts = tblTtpdgmsts;
        this.tenHoSo = tenHoSo;
        this.created = created;
        this.modified = modified;
        this.status = status;
    }
    public TblTtpdgmstsDinhKem(TblUsers tblUsers, TblDocument tblDocument, TblTtpdgmsts tblTtpdgmsts, String tenHoSo, Date created, Date modified, byte status) {
       this.tblUsers = tblUsers;
       this.tblDocument = tblDocument;
       this.tblTtpdgmsts = tblTtpdgmsts;
       this.tenHoSo = tenHoSo;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getTtpdgmstsDinhKemId() {
        return this.ttpdgmstsDinhKemId;
    }
    
    public void setTtpdgmstsDinhKemId(Long ttpdgmstsDinhKemId) {
        this.ttpdgmstsDinhKemId = ttpdgmstsDinhKemId;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public TblDocument getTblDocument() {
        return this.tblDocument;
    }
    
    public void setTblDocument(TblDocument tblDocument) {
        this.tblDocument = tblDocument;
    }
    public TblTtpdgmsts getTblTtpdgmsts() {
        return this.tblTtpdgmsts;
    }
    
    public void setTblTtpdgmsts(TblTtpdgmsts tblTtpdgmsts) {
        this.tblTtpdgmsts = tblTtpdgmsts;
    }
    public String getTenHoSo() {
        return this.tenHoSo;
    }
    
    public void setTenHoSo(String tenHoSo) {
        this.tenHoSo = tenHoSo;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


