package vn.softech.hibernate;
// Generated Mar 24, 2012 3:21:23 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtpapbdtnsChuyenhs generated by hbm2java
 */
public class TblTtpapbdtnsChuyenhs  implements java.io.Serializable {


     private Long ttpapbdtnsChuyenhsId;
     private TblUsers tblUsersByUsersChuyenId;
     private TblTtpapbdtns tblTtpapbdtns;
     private TblUsers tblUsersByUsersNhanId;
     private Date ngayChuyen;
     private String ghiChu;
     private Byte status;

    public TblTtpapbdtnsChuyenhs() {
    }

	
    public TblTtpapbdtnsChuyenhs(TblUsers tblUsersByUsersChuyenId, TblTtpapbdtns tblTtpapbdtns, TblUsers tblUsersByUsersNhanId, Date ngayChuyen) {
        this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
        this.tblTtpapbdtns = tblTtpapbdtns;
        this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
        this.ngayChuyen = ngayChuyen;
    }
    public TblTtpapbdtnsChuyenhs(TblUsers tblUsersByUsersChuyenId, TblTtpapbdtns tblTtpapbdtns, TblUsers tblUsersByUsersNhanId, Date ngayChuyen, String ghiChu, Byte status) {
       this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
       this.tblTtpapbdtns = tblTtpapbdtns;
       this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
       this.ngayChuyen = ngayChuyen;
       this.ghiChu = ghiChu;
       this.status = status;
    }
   
    public Long getTtpapbdtnsChuyenhsId() {
        return this.ttpapbdtnsChuyenhsId;
    }
    
    public void setTtpapbdtnsChuyenhsId(Long ttpapbdtnsChuyenhsId) {
        this.ttpapbdtnsChuyenhsId = ttpapbdtnsChuyenhsId;
    }
    public TblUsers getTblUsersByUsersChuyenId() {
        return this.tblUsersByUsersChuyenId;
    }
    
    public void setTblUsersByUsersChuyenId(TblUsers tblUsersByUsersChuyenId) {
        this.tblUsersByUsersChuyenId = tblUsersByUsersChuyenId;
    }
    public TblTtpapbdtns getTblTtpapbdtns() {
        return this.tblTtpapbdtns;
    }
    
    public void setTblTtpapbdtns(TblTtpapbdtns tblTtpapbdtns) {
        this.tblTtpapbdtns = tblTtpapbdtns;
    }
    public TblUsers getTblUsersByUsersNhanId() {
        return this.tblUsersByUsersNhanId;
    }
    
    public void setTblUsersByUsersNhanId(TblUsers tblUsersByUsersNhanId) {
        this.tblUsersByUsersNhanId = tblUsersByUsersNhanId;
    }
    public Date getNgayChuyen() {
        return this.ngayChuyen;
    }
    
    public void setNgayChuyen(Date ngayChuyen) {
        this.ngayChuyen = ngayChuyen;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


