package vn.softech.hibernate;
// Generated Feb 27, 2012 10:59:38 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblTtpapbdtnsButPhe generated by hbm2java
 */
public class TblTtpapbdtnsButPhe  implements java.io.Serializable {


     private Long ttpapbdtnsButPheId;
     private TblTtpapbdtns tblTtpapbdtns;
     private TblUsers tblUsers;
     private String noiDung;
     private Date created;
     private Date modified;
     private byte status;

    public TblTtpapbdtnsButPhe() {
    }

    public TblTtpapbdtnsButPhe(TblTtpapbdtns tblTtpapbdtns, TblUsers tblUsers, String noiDung, Date created, Date modified, byte status) {
       this.tblTtpapbdtns = tblTtpapbdtns;
       this.tblUsers = tblUsers;
       this.noiDung = noiDung;
       this.created = created;
       this.modified = modified;
       this.status = status;
    }
   
    public Long getTtpapbdtnsButPheId() {
        return this.ttpapbdtnsButPheId;
    }
    
    public void setTtpapbdtnsButPheId(Long ttpapbdtnsButPheId) {
        this.ttpapbdtnsButPheId = ttpapbdtnsButPheId;
    }
    public TblTtpapbdtns getTblTtpapbdtns() {
        return this.tblTtpapbdtns;
    }
    
    public void setTblTtpapbdtns(TblTtpapbdtns tblTtpapbdtns) {
        this.tblTtpapbdtns = tblTtpapbdtns;
    }
    public TblUsers getTblUsers() {
        return this.tblUsers;
    }
    
    public void setTblUsers(TblUsers tblUsers) {
        this.tblUsers = tblUsers;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


