package vn.softech.hibernate;
// Generated Feb 17, 2012 3:49:07 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblUsers generated by hbm2java
 */
public class TblUsers  implements java.io.Serializable {

     private Long usersId;
     private String firstName;
     private String lastName;
     private String username;
     private String password;
     private String email;
     private boolean active;
     private Date created;
     private Date modified;
     private byte status;
     private TblPhongBan tblPhongBan;
     private List<TblAnswer> tblAnswers = new ArrayList<TblAnswer>();
     private List<TblQuestionAssign> tblQuestionAssignsForAssigner = new ArrayList<TblQuestionAssign>();
     private List<TblUsersGroups> tblUsersGroupses = new ArrayList<TblUsersGroups>();
     private List<TblQuestionAssign> tblQuestionAssignsForAssignToUsersId = new ArrayList<TblQuestionAssign>();

    public TblUsers() {
    }

	
    public TblUsers(String firstName, String lastName, String username, String password, String email, boolean active, Date created, Date modified, byte status) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.password = password;
        this.email = email;
        this.active = active;
        this.created = created;
        this.modified = modified;
        this.status = status;
    }
    public TblUsers(String firstName, String lastName, String username, String password, String email, boolean active, Date created, Date modified, byte status, List<TblAnswer> tblAnswers, List<TblQuestionAssign> tblQuestionAssignsForAssigner, List<TblUsersGroups> tblUsersGroupses, List<TblQuestionAssign> tblQuestionAssignsForAssignToUsersId) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.username = username;
       this.password = password;
       this.email = email;
       this.active = active;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.tblAnswers = tblAnswers;
       this.tblQuestionAssignsForAssigner = tblQuestionAssignsForAssigner;
       this.tblUsersGroupses = tblUsersGroupses;
       this.tblQuestionAssignsForAssignToUsersId = tblQuestionAssignsForAssignToUsersId;
    }
   
    public Long getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(Long usersId) {
        this.usersId = usersId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public List<TblAnswer> getTblAnswers() {
        return this.tblAnswers;
    }
    
    public void setTblAnswers(List<TblAnswer> tblAnswers) {
        this.tblAnswers = tblAnswers;
    }
    public List<TblQuestionAssign> getTblQuestionAssignsForAssigner() {
        return this.tblQuestionAssignsForAssigner;
    }
    
    public void setTblQuestionAssignsForAssigner(List<TblQuestionAssign> tblQuestionAssignsForAssigner) {
        this.tblQuestionAssignsForAssigner = tblQuestionAssignsForAssigner;
    }
    public List<TblUsersGroups> getTblUsersGroupses() {
        return this.tblUsersGroupses;
    }
    
    public void setTblUsersGroupses(List<TblUsersGroups> tblUsersGroupses) {
        this.tblUsersGroupses = tblUsersGroupses;
    }
    public List<TblQuestionAssign> getTblQuestionAssignsForAssignToUsersId() {
        return this.tblQuestionAssignsForAssignToUsersId;
    }
    
    public void setTblQuestionAssignsForAssignToUsersId(List<TblQuestionAssign> tblQuestionAssignsForAssignToUsersId) {
        this.tblQuestionAssignsForAssignToUsersId = tblQuestionAssignsForAssignToUsersId;
    }

	public TblPhongBan getTblPhongBan() {
		return tblPhongBan;
	}


	public void setTblPhongBan(TblPhongBan tblPhongBan) {
		this.tblPhongBan = tblPhongBan;
	}




}


