package vn.softech.hibernate;
// Generated Jan 6, 2012 3:11:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TblVoteResult generated by hbm2java
 */
public class TblVoteResult  implements java.io.Serializable {


     private Long voteResultId;
     private TblVoteItem tblVoteItem;
     private String ipAddress;
     private Date voteDate;

    public TblVoteResult() {
    }

    public TblVoteResult(TblVoteItem tblVoteItem, String ipAddress, Date voteDate) {
       this.tblVoteItem = tblVoteItem;
       this.ipAddress = ipAddress;
       this.voteDate = voteDate;
    }
   
    public Long getVoteResultId() {
        return this.voteResultId;
    }
    
    public void setVoteResultId(Long voteResultId) {
        this.voteResultId = voteResultId;
    }
    public TblVoteItem getTblVoteItem() {
        return this.tblVoteItem;
    }
    
    public void setTblVoteItem(TblVoteItem tblVoteItem) {
        this.tblVoteItem = tblVoteItem;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Date getVoteDate() {
        return this.voteDate;
    }
    
    public void setVoteDate(Date voteDate) {
        this.voteDate = voteDate;
    }




}


