package vn.softech.hibernate;
// Generated Mar 19, 2012 8:28:27 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * TblVideo generated by hbm2java
 */
public class TblVideo  implements java.io.Serializable {


     private Long videoId;
     private String title;
     private String url;
     private Date created;
     private Date modified;
     private Byte status;
     private Byte priority;

    public TblVideo() {
    }

	
    public TblVideo(String title, String url, Date created, Date modified) {
        this.title = title;
        this.url = url;
        this.created = created;
        this.modified = modified;
    }
    public TblVideo(String title, String url, Date created, Date modified, Byte status, Byte priority) {
       this.title = title;
       this.url = url;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.priority = priority;
    }
   
    public Long getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(Long videoId) {
        this.videoId = videoId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Byte getPriority() {
        return this.priority;
    }
    
    public void setPriority(Byte priority) {
        this.priority = priority;
    }




}


