package vn.softech.hibernate;
// Generated Jan 6, 2012 3:11:47 PM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TblVoteItem generated by hbm2java
 */
public class TblVoteItem  implements java.io.Serializable {


     private Long voteItemId;
     private TblVote tblVote;
     private String content;
     private Date created;
     private Long status;
     private List<TblVoteResult> voteResults = new ArrayList<TblVoteResult>();

    public TblVoteItem() {
    }

	
    public TblVoteItem(TblVote tblVote, String content, Date created, Long status) {
        this.tblVote = tblVote;
        this.content = content;
        this.created = created;
        this.setStatus(status);
    }
    public TblVoteItem(TblVote tblVote, String content, Date created, Long status, List<TblVoteResult> voteResults) {
       this.tblVote = tblVote;
       this.content = content;
       this.created = created;
       this.setStatus(status);
       this.setVoteResults(voteResults);
    }
   
    public Long getVoteItemId() {
        return this.voteItemId;
    }
    
    public void setVoteItemId(Long voteItemId) {
        this.voteItemId = voteItemId;
    }
    public TblVote getTblVote() {
        return this.tblVote;
    }
    
    public void setTblVote(TblVote tblVote) {
        this.tblVote = tblVote;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Long getStatus() {
		return status;
	}


	public void setStatus(Long status) {
		this.status = status;
	}


	public List<TblVoteResult> getVoteResults() {
		return voteResults;
	}


	public void setVoteResults(List<TblVoteResult> voteResults) {
		this.voteResults = voteResults;
	}
}


